name: Cleanup Flex testing endpoint

on:
    pull_request_target:
        types: [ closed ]

defaults:
    run:
        shell: bash

jobs:
    call-flex-cleanup:
        uses: piotrkardasz/bitbag-recipes/.github/workflows/callable-flex-cleanup.yml@workflows
